services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/tools:/etc/nginx/ssl/
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - front

  front:
    container_name: front
    build:
      context: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
