# Generated by Django 5.1.1 on 2024-12-13 20:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickerPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('number_of_matches', models.IntegerField()),
                ('average_click_speed', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ClickerGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('time', models.IntegerField()),
                ('players', models.ManyToManyField(related_name='clicker_games', to='clicker.clickerplayer')),
            ],
        ),
    ]
