# Generated by Django 5.1.1 on 2024-12-11 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clicker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player',
            new_name='ClickerPlayer',
        ),
    ]
