# Generated by Django 5.1.1 on 2024-12-26 19:10

import intrauth.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntraUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('intra_login', models.CharField(max_length=8)),
                ('avatar', models.CharField(max_length=100)),
                ('wallet', models.IntegerField(default=0)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            managers=[
                ('objects', intrauth.managers.IntraUserManager()),
            ],
        ),
    ]
