# Generated by Django 5.1.1 on 2024-12-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrauth', '0002_intrauser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrauser',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intrauser',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='intrauser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='intrauser',
            name='intra_login',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
