groups:
  - name: infra_alerts
    rules:
      - alert: High CPU Usage
        expr: sum(rate(node_cpu_seconds_total{mode="idle"}[5m])) by (instance) < 0.1
        for: 15sec
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage detected on instance {{ $labels.instance}}"
          description: "CPU usage is above 90% for more than 15 seconds"
