groups:
  - name: infra_alerts
    rules:
      - alert: HighCPUUsage
        expr: sum(rate(node_cpu_seconds_total{mode="idle"}[5m])) by (instance) > 0.1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage detected on instance {{ $labels.instance }}"
          description: "CPU usage is above 90% for more than 15 seconds"

      - alert: HostOutOfDiskSpace
        expr: round(node_filesystem_avail_bytes{mountpoint="/"}/node_filesystem_size_byte{mountpoint="/"}*100,0.01) < 20
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Host running out of disk space (instance {{ $labels.instance }})"
          description: "Disk is almost full {{ $value }}%"

