global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

        # - job_name: 'nodejs-app'
        # static_configs:
        # - targets: ['localhost:5000']

rule_files:
  - 'prometheus_rules.yml'

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - 'alerting:9093'
