### user your own logins and passwords ;)

global:
  smtp_smarthost: '{{ .Env.SMTP_SERVER }}'
  smtp_from: '{{ .Env.EMAIL_USER }}'
  smtp_auth_username: '{{ .Env.EMAIL_USER }}'
  smtp_auth_password: '{{ .Env.SMTP_SERVER_PASSWORD }}'
  smtp_require_tls: true

route:
  receiver: 'email'
  group_wait: 10s

receivers:
  - name: 'email'
    email_configs:
      - to: '{{ .Env.RECIPIENT }}'
