# Generated by Django 5.1.1 on 2024-10-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='test_value',
            field=models.IntegerField(default=0),
        ),
    ]
