# Generated by Django 5.1.1 on 2024-10-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_game_test_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
